<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2">      
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Azure.Identity" Version="1.13.2" />
    <PackageReference Include="EPR.Common.Functions" Version="1.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
   <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <SonarQubeSetting Include="sonar.coverage.exclusions">
      <Value>
        **/CheckSplitterValidationError.cs
      </Value>
    </SonarQubeSetting>
    <SonarQubeSetting Include="sonar.cpd.exclusions">
      <Value>
        **/CheckSplitterValidationError.cs,**/CheckSplitterValidationWarning.cs,**/ProducerValidationError.cs,**/ProducerValidationWarning.cs
      </Value>
    </SonarQubeSetting>
  </ItemGroup>

</Project>